#<<: !include ./secrets.yaml // implied

esphome:
  name: autoradiator-1

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hapwd

ota:
  password: !secret hapwd

wifi:
  ssid: !secret wifissid
  password: !secret wifipwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Autoradiator-1 Fallback Hotspot"
    password: !secret oopspwd

  manual_ip:
    static_ip: 192.168.50.79
    gateway: 192.168.50.1
    subnet: 255.255.255.0
    dns1: 192.168.50.1

web_server:
  port: 80

captive_portal:

sensor:
  - platform: adc
    pin: A0
    name: "Temperature"
    id: "Temperature"
    unit_of_measurement: "°C"
    update_interval: 500ms
    filters:
      - multiply: 330

switch:
  - platform: gpio 
    pin: D7  #D7
    name: MotorIN1
    id: MotorIN1
  - platform: gpio 
    pin: D6  #D6
    name: MotorIN2
    id: MotorIN2


climate:
  - platform: thermostat
    name: "Radiator"
    sensor: "Temperature"
    visual:
      max_temperature: 115 °C
    min_heating_off_time: 1s
    min_heating_run_time: 1s
    min_idle_time: 1s
    heat_action:
      - switch.turn_on: MotorIN1
      - switch.turn_off: MotorIN2
      - delay: 10s
      - switch.turn_off: MotorIN1
    idle_action:
      - switch.turn_on: MotorIN2
      - switch.turn_off: MotorIN1
      - delay: 11s
      - switch.turn_off: MotorIN2
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 20 °C
